spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "test_user"
    password: "test_password"
    url: jdbc:postgresql://192.168.217.128:5432/test_db
  jpa:
    hibernate:
      ddl-auto: update